/* tslint:disable */
/* eslint-disable */
/**
 * TaskManager
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { WorkVisit } from '../models';
import { WorkVisitScheme } from '../models';
/**
 * WorkVisitControllersApi - axios parameter creator
 * @export
 */
export const WorkVisitControllersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {WorkVisitScheme} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerWorkVisit: async (body?: WorkVisitScheme, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/visit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WorkVisitControllersApi - functional programming interface
 * @export
 */
export const WorkVisitControllersApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {WorkVisitScheme} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerWorkVisit(body?: WorkVisitScheme, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<WorkVisit>>> {
            const localVarAxiosArgs = await WorkVisitControllersApiAxiosParamCreator(configuration).registerWorkVisit(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * WorkVisitControllersApi - factory interface
 * @export
 */
export const WorkVisitControllersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {WorkVisitScheme} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerWorkVisit(body?: WorkVisitScheme, options?: AxiosRequestConfig): Promise<AxiosResponse<WorkVisit>> {
            return WorkVisitControllersApiFp(configuration).registerWorkVisit(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WorkVisitControllersApi - object-oriented interface
 * @export
 * @class WorkVisitControllersApi
 * @extends {BaseAPI}
 */
export class WorkVisitControllersApi extends BaseAPI {
    /**
     * 
     * @param {WorkVisitScheme} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkVisitControllersApi
     */
    public async registerWorkVisit(body?: WorkVisitScheme, options?: AxiosRequestConfig) : Promise<AxiosResponse<WorkVisit>> {
        return WorkVisitControllersApiFp(this.configuration).registerWorkVisit(body, options).then((request) => request(this.axios, this.basePath));
    }
}
