/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FileModel } from './file-model';
import { UserWorkTypes } from './user-work-types';
 /**
 * 
 *
 * @export
 * @interface AttendanceUserScheme
 */
export interface AttendanceUserScheme {

    /**
     * @type {string}
     * @memberof AttendanceUserScheme
     */
    email?: string | null;

    /**
     * @type {string}
     * @memberof AttendanceUserScheme
     */
    fullName?: string | null;

    /**
     * @type {boolean}
     * @memberof AttendanceUserScheme
     */
    blocked?: boolean;

    /**
     * @type {FileModel}
     * @memberof AttendanceUserScheme
     */
    avatar?: FileModel;

    /**
     * @type {UserWorkTypes}
     * @memberof AttendanceUserScheme
     */
    workType?: UserWorkTypes;
}
