/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GroupRoles } from './group-roles';
 /**
 * 
 *
 * @export
 * @interface CreateGroupScheme
 */
export interface CreateGroupScheme {

    /**
     * @type {string}
     * @memberof CreateGroupScheme
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof CreateGroupScheme
     */
    teamId?: string;

    /**
     * @type {GroupRoles}
     * @memberof CreateGroupScheme
     */
    role?: GroupRoles;
}
