/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { UserModel } from './user-model';
 /**
 * 
 *
 * @export
 * @interface Group
 */
export interface Group {

    /**
     * @type {string}
     * @memberof Group
     */
    id?: string;

    /**
     * @type {string}
     * @memberof Group
     */
    name: string;

    /**
     * @type {string}
     * @memberof Group
     */
    role: string;

    /**
     * @type {Array<UserModel>}
     * @memberof Group
     */
    users?: Array<UserModel> | null;

    /**
     * @type {UserModel}
     * @memberof Group
     */
    owner?: UserModel;
}
