/* tslint:disable */
/* eslint-disable */
/**
 * TaskManager
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TaskModel } from './task-model';
 /**
 * 
 *
 * @export
 * @interface TaskTag
 */
export interface TaskTag {

    /**
     * @type {string}
     * @memberof TaskTag
     */
    id: string;

    /**
     * @type {string}
     * @memberof TaskTag
     */
    name: string;

    /**
     * @type {Array<TaskModel>}
     * @memberof TaskTag
     */
    tasks?: Array<TaskModel> | null;
}
