/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface TaskType
 */
export interface TaskType {

    /**
     * @type {string}
     * @memberof TaskType
     */
    id?: string;

    /**
     * @type {string}
     * @memberof TaskType
     */
    name?: string | null;
}
