/* tslint:disable */
/* eslint-disable */
/**
 * TaskManager
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateUserScheme
 */
export interface UpdateUserScheme {

    /**
     * @type {string}
     * @memberof UpdateUserScheme
     */
    email?: string | null;

    /**
     * @type {string}
     * @memberof UpdateUserScheme
     */
    password?: string | null;

    /**
     * @type {string}
     * @memberof UpdateUserScheme
     */
    fullName?: string | null;

    /**
     * @type {string}
     * @memberof UpdateUserScheme
     */
    avatarId?: string | null;
}
