/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FileModel } from './file-model';
import { WorkVisit } from './work-visit';
 /**
 * 
 *
 * @export
 * @interface UserModel
 */
export interface UserModel {

    /**
     * @type {string}
     * @memberof UserModel
     */
    id?: string;

    /**
     * @type {string}
     * @memberof UserModel
     */
    fullName?: string | null;

    /**
     * @type {string}
     * @memberof UserModel
     */
    email?: string | null;

    /**
     * @type {string}
     * @memberof UserModel
     */
    hashedPassword?: string | null;

    /**
     * @type {boolean}
     * @memberof UserModel
     */
    blocked?: boolean;

    /**
     * @type {FileModel}
     * @memberof UserModel
     */
    avatar?: FileModel;

    /**
     * @type {string}
     * @memberof UserModel
     */
    telegram?: string | null;

    /**
     * @type {FileModel}
     * @memberof UserModel
     */
    banner?: FileModel;

    /**
     * @type {string}
     * @memberof UserModel
     */
    workType?: string | null;

    /**
     * @type {Array<WorkVisit>}
     * @memberof UserModel
     */
    workVisits?: Array<WorkVisit> | null;
}
