/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DayTimetable } from './day-timetable';
 /**
 * 
 *
 * @export
 * @interface WorkVisit
 */
export interface WorkVisit {

    /**
     * @type {string}
     * @memberof WorkVisit
     */
    id: string;

    /**
     * @type {Date}
     * @memberof WorkVisit
     */
    visitedAt?: Date;

    /**
     * @type {Date}
     * @memberof WorkVisit
     */
    endedAt?: Date;

    /**
     * @type {DayTimetable}
     * @memberof WorkVisit
     */
    dayTimetable: DayTimetable;
}
